version: '3.1'

services:
  webserver:
    image: webdevops/php-nginx:7.2
    container_name: webserver
    restart: always
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.htm
    ports:
      - "81:80"